### ISSUE TITLE
Lab 5 - External Data - General questions

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-7001-Create-and-manage-canvas-apps-with-Power-Apps#7]
# Lab 5 - External Data

General Questions that don't make complete sense to me:

1.  In Exercise 1 and 2 we create a SharePoint List and then eventually add that as a Data Source as a Gallery in the Canvas App...but it's never actually used.  We don't add data to the List, and it's never referenced again in the Labs.  So it would be nice to have an explanation "why" we went through that trouble.      Like should we build a different app that uses SharePoint as the data source instead of the Dataverse?

2. Exercise 3 has us create a Collection...but it's never used anywhere.  We add records to the Collection...but why?  It's never referenced again.

**Comment by julians1966** [comment]
These steps are to show how to connect to non-Dataverse data sources and to show how to create collections as these topics are within the scope of the applied skills
There is a limit as to how much can be performed in the labs in the time available and was not able to use these further

**Comment by miberr** [comment]
I agree with @tylerfarmer1, it's really weird... If time is an issue maybe remove that altogether? I mean there are other MOC courses available for that as well.

Another option would be adding the steps to actually use it as a optional task. I think that could actually be quite beneficial since people vary in speed doing labs.

**Comment by tylerfarmer1** [comment]
I'm teaching this class this week;  I'm going to skip having the students add a SharePoint list to this app.  I'll do it as a demo showing that I could use a SharePoint list as a data source instead of the Dataverse and/or Excel, but I'm not going to have students do it.

**Comment by CeleneA** [comment]
Our objective is to create modular labs, so this design is intentional.
