### ISSUE TITLE
Lab 1 - Power Platform Major Change, broke the lab

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-7001-Create-and-manage-canvas-apps-with-Power-Apps#9]
# Lab/Demo: Lab 1 - Create a canvas app from data
## Exercise 3 - Build a canvas app with Copilot

Description of issue:

Just this week (or last week) the Power Platform interface changed significantly.  

It used to be that when you use Copilot to automatically generate an app, it created a single table (which you could edit the structure) and then create the 3-screen app.

Now it creates multiple tables.

For Exercise 3, you enter the prompt "Track coffee machine repairs for customers and assign repairs to technicians" and it used to create just 1 table.   Now it creates 3 tables (Technician, Customer and Repair), and in my test it did not create all the relationships that it needs to, and the app creation doesn't work correctly, etc.

For now, I'm having students skip Exercise 3.

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. We will be able to provide feedback soon
